version: "0.alpha.{build}"
skip_non_tags: true
image: Visual Studio 2019
platform: x64
environment:
  nodejs_version: "6"
  SENTRY_URL: http://lvwl.to2x.ovh:9000/
  SENTRY_API_KEY:
    secure: 
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
cache:
  - C:\gstreamer\1.0\x86_64
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - c:\tools\vcpkg\installed\
install:
  #- cmd: choco install pkgconfiglite
  - cd c:\tools\vcpkg
  - vcpkg install miniupnpc openssl
  - vcpkg integrate install
  - npm install -g @sentry/cli --unsafe-perm
  # - appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-devel-msvc-x86_64-1.16.2.msi
  # - appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-msvc-x86_64-1.16.2.msi
  # - msiexec /i gstreamer-1.0-devel-msvc-x86_64-1.16.2.msi /quiet /qn /norestart /log install-devel.log ADDLOCAL=ALL
  # - msiexec /i gstreamer-1.0-msvc-x86_64-1.16.2.msi /quiet /qn /norestart /log install.log ADDLOCAL=ALL
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --config Release -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DOPENSSL_BIN_DIR="C:\OpenSSL-v111-Win64\bin" -DQT_MAIN_DIR="C:\Qt\5.13" -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 .. 
  - cmd: cd ..
  - cmd: cmake --build ./build --target package --config Release
  - cmd: cmake --build ./build --target zipForDeploy --config Release
artifacts:
  - path: build/repository.zip
    name: IFW_Repo
  - path: build/installer.zip
    name: IFW_Installer
before_build:
  - sentry-cli login
  - sentry-cli difutil bundle-sources /debugSymbols
  - sentry-cli upload-dif -o livingwill -p rpgrpz /debugSymbols
deploy:
  - provider: BinTray
    username: amphaal
    api_key:
      secure: yNlQ0sbe2mYcm13rWA7wKuISHE93lndKeIEyGPbHz3mr2oDYQWCNTWXVsExiSJan
    subject: amphaal
    repo: rpgrpz
    package: rpgrpz-ifw-win
    version: latest
    publish: true
    override: true
    explode: true
    artifact: IFW_Repo
  - provider: BinTray
    username: amphaal
    api_key:
      secure: yNlQ0sbe2mYcm13rWA7wKuISHE93lndKeIEyGPbHz3mr2oDYQWCNTWXVsExiSJan
    subject: amphaal
    repo: rpgrpz
    package: rpgrpz-win
    version: latest
    publish: true
    override: true
    explode: true
    artifact: IFW_Installer