version: "0.alpha.{build}"
skip_non_tags: true
image: Visual Studio 2019
platform: x64
configuration: Release
environment:
  #nodejs_version: "6"
  SENTRY_AUTH_TOKEN:
    secure: zQZbXTbRnxBA1W6zaGe7Erg4A0PMMcAnNmk3x/RGCPSB6GyaVIzAvbHJD6nKkesBEENXwlstV3YOW+PtvPAJ58px7xEhebXSFQ63lw3b2Qo=
cache:
  - C:\gstreamer\1.0\x86_64
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
install:
  # - choco install pkgconfiglite
  # - npm install -g @sentry/cli --unsafe-perm
  # - appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-devel-mingw-x86_64-1.16.2.msi
  # - appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-mingw-x86_64-1.16.2.msi
  # - msiexec /i gstreamer-1.0-devel-mingw-x86_64-1.16.2.msi /quiet /qn /norestart /log install-devel.log ADDLOCAL=ALL
  # - msiexec /i gstreamer-1.0-mingw-x86_64-1.16.2.msi /quiet /qn /norestart /log install.log ADDLOCAL=ALL
build_script:
  - cmd: mkdir _genRelease
  - cmd: cd _genRelease
  - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/win-appveyor.cmake -GNinja .. 
  - cmd: cd ..
  - cmd: cmake --build ./_genRelease --target zipForDeploy
#after_build:
# https://docs.sentry.io/cli/dif/; https://docs.sentry.io/cli/configuration/
#  - sentry-cli --url http://zonme.to2x.ovh:9000/ login
#  - sentry-cli difutil bundle-sources /debugSymbols
#  - sentry-cli upload-dif -o livingwill -p rpgrpz /debugSymbols
artifacts:
  - path: build/repository.zip
    name: IFW_Repo
  - path: build/installer.zip
    name: IFW_Installer
# deploy:
#   - provider: BinTray
#     username: amphaal
#     api_key:
#       secure: yNlQ0sbe2mYcm13rWA7wKuISHE93lndKeIEyGPbHz3mr2oDYQWCNTWXVsExiSJan
#     subject: amphaal
#     repo: rpgrpz
#     package: rpgrpz-ifw-win
#     version: latest
#     publish: true
#     override: true
#     explode: true
#     artifact: IFW_Repo
#   - provider: BinTray
#     username: amphaal
#     api_key:
#       secure: yNlQ0sbe2mYcm13rWA7wKuISHE93lndKeIEyGPbHz3mr2oDYQWCNTWXVsExiSJan
#     subject: amphaal
#     repo: rpgrpz
#     package: rpgrpz-win
#     version: latest
#     publish: true
#     override: true
#     explode: true
#     artifact: IFW_Installer