version: 0.19.1.{build}
image: Visual Studio 2019
#build:
  #verbosity: detailed
platform: x64
install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: conan remote add --force rhard https://api.bintray.com/conan/rhard/conan
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. -s build_type=Release --build missing
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 16 2019 Win64"
  - cmd: cd ..
  - cmd: cmake --build ./build --config Release --target package
test_script:
  - cmd: cd build/bin
  - cmd: ls