version: 0.19.1.{build}
image: Visual Studio 2017
platform: x64
cache:
  - C:\gstreamer\1.0\x86_64
install:
  - cmd: choco install pkgconfiglite
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: conan remote add --force rhard https://api.bintray.com/conan/rhard/conan
  - appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.16.1/gstreamer-1.0-devel-msvc-x86_64-1.16.1.msi
  - appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.16.1/gstreamer-1.0-msvc-x86_64-1.16.1.msi
  - msiexec /i gstreamer-1.0-devel-msvc-x86_64-1.16.1.msi /quiet /qn /norestart /log install-devel.log ADDLOCAL=ALL
  - msiexec /i gstreamer-1.0-msvc-x86_64-1.16.1.msi /quiet /qn /norestart /log install.log ADDLOCAL=ALL
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. -s build_type=Release --build missing
  - cmd: cmake --config Release -DQT_MAIN_DIR="C:\Qt\5.13" -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" .. 
  - cmd: cd ..
  - cmd: cmake --build ./build -DQT_MAIN_DIR="C:\Qt\5.13" --config Release --target package
test_script:
  - cmd: cd build/bin
  - cmd: ls