############################
### CPACK CONFIG + Qt ITW ##
############################

if (WIN32)
    INSTALL(DIRECTORY ${CMAKE_BINARY_DIR}/bin/ DESTINATION .)
endif (WIN32)

SET(CPACK_MONOLITHIC_INSTALL 1)

SET(RPGRPZ_DESCRIPTION "RPGRPZ")

SET(CPACK_IFW_PACKAGE_WIZARD_STYLE "Modern")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${RPGRPZ_DESCRIPTION})
SET(CPACK_IFW_PACKAGE_PUBLISHER ${APP_PUBLISHER})
SET(CPACK_IFW_PACKAGE_START_MENU_DIRECTORY ${APP_PUBLISHER})
SET(CPACK_IFW_PRODUCT_URL ${APP_MAIN_URL})
SET(CPACK_IFW_TARGET_DIRECTORY "@ApplicationsDirX64@/RPGRPZ")

if (WIN32)
    SET(CPACK_IFW_ROOT "C:/Qt/QtIFW-3.0.6")
    SET(RPGRPZ_REMOTE_SERVER_PATH "//192.168.0.12/www/RPGRPZ")
    SET(RPGRPZ_REMOTE_SERVER_PLATFORM_FOLDER "win")
    SET(RPGRPZ_INSTALLER_EXTENSION ".exe")
    SET(RPGRPZ_ICON_EXT ".ico")
endif (WIN32)

#icons
SET(CPACK_IFW_PACKAGE_LOGO ${CMAKE_CURRENT_SOURCE_DIR}/resources/icons/RPGRPZ_64.png)
SET(CPACK_IFW_PACKAGE_ICON ${CMAKE_CURRENT_SOURCE_DIR}/resources/icons/package${RPGRPZ_ICON_EXT})

SET(RPGRPZ_REMOTE_SERVER_DOWNLOAD_PATH ${RPGRPZ_REMOTE_SERVER_PATH}/downloads/${RPGRPZ_REMOTE_SERVER_PLATFORM_FOLDER})
SET(RPGRPZ_REMOTE_SERVER_PACKAGES_PATH ${RPGRPZ_REMOTE_SERVER_PATH}/packages/${RPGRPZ_REMOTE_SERVER_PLATFORM_FOLDER})

SET(CPACK_GENERATOR IFW)
INCLUDE(CPack)
INCLUDE(CPackIFW)

cpack_add_component(${PROJECT_NAME}
                    DISPLAY_NAME ${PROJECT_NAME}
                    DESCRIPTION ${RPGRPZ_DESCRIPTION}
                    REQUIRED
)

cpack_ifw_configure_component(${PROJECT_NAME} 
                    ESSENTIAL
                    FORCED_INSTALLATION
                    NAME "com.lvwl.RPGRPZ.core"
                    DESCRIPTION ${RPGRPZ_DESCRIPTION}
                    DEFAULT TRUE
)

cpack_ifw_add_repository(coreRepo URL ${APP_ROOT_URL}/RPGRPZ/packages/${RPGRPZ_REMOTE_SERVER_PLATFORM_FOLDER})

#############
## Publish ## 
#############

SET(RPGRPZ_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME})
SET(RPGRPZ_PACKAGED_PATH ${CMAKE_BINARY_DIR}/_CPack_Packages/${CPACK_SYSTEM_NAME}/IFW/${RPGRPZ_PACKAGE_FILE_NAME})
SET(RPGRPZ_PACKAGED_INSTALLER_PATH ${RPGRPZ_PACKAGED_PATH}${RPGRPZ_INSTALLER_EXTENSION})
SET(RPGRPZ_PACKAGED_REPOSITORY_PATH ${RPGRPZ_PACKAGED_PATH}/repository)

#install CoreUtils for Win32 if mv missing
add_custom_target(publishPackage 
    COMMAND ${CMAKE_COMMAND} --build . --config Release --target package
    COMMAND cp -rf ${RPGRPZ_PACKAGED_INSTALLER_PATH} ${RPGRPZ_REMOTE_SERVER_DOWNLOAD_PATH}
    COMMAND cp -rf ${RPGRPZ_PACKAGED_REPOSITORY_PATH}/* ${RPGRPZ_REMOTE_SERVER_PACKAGES_PATH}
)