#include "payloads/AddedPayload.hpp"
#include "payloads/FocusedPayload.hpp"
#include "payloads/LayerChangedPayload.hpp"
#include "payloads/MovedPayload.hpp"
#include "payloads/RemovedPayload.hpp"
#include "payloads/ResetPayload.hpp"
#include "payloads/SelectedPayload.hpp"