// RPG-RPZ
// A simple Pen & Paper experience
// Copyright (C) 2019-2020 Guillaume Vara

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// Any graphical or audio resources available within the source code may
// use a different license and copyright : please refer to their metadata
// for further details. Resources without explicit references to a
// different license and copyright still refer to this GPL.

#pragma once

// This file is autogenerated by build_templates/_version.h with CMAKE
#define APP_PUBLISHER "${APP_PUBLISHER}"
#define APP_PATCHNOTE_URL "${APP_PATCHNOTE_URL}"
#define APP_NAME "${PROJECT_NAME}"
#define APP_CURRENT_VERSION "${CMAKE_PROJECT_VERSION}"
#define APP_FULL_DENOM "${PROJECT_NAME} ${CMAKE_PROJECT_VERSION}"
#define GITHUB_VERSION_NAME "${PROJECT_NAME_LOWER}@${CMAKE_PROJECT_VERSION}"
#define APP_DEFAULT_URL "${CMAKE_PROJECT_HOMEPAGE_URL}"
#define SENTRY_ENDPOINT "${SENTRY_ENDPOINT}"
