// RPG-RPZ
// A simple Pen & Paper experience
// Copyright (C) 2019-2020 Guillaume Vara

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// Any graphical or audio resources available within the source code may
// use a different license and copyright : please refer to their metadata
// for further details. Resources without explicit references to a
// different license and copyright still refer to this GPL.

#pragma once

// This file is autogenerated by build_templates/_version.h with CMAKE
#define APP_PUBLISHER "LVWL"
#define APP_PATCHNOTE_URL "https://github.com/Amphaal/rpgrpz/releases"
#define APP_NAME "RPGRPZ"
#define APP_CURRENT_VERSION "1.0.22"
#define APP_FULL_DENOM "RPGRPZ 1.0.22"
#define GITHUB_VERSION_NAME "rpgrpz@1.0.22"
#define APP_DEFAULT_URL "https://github.com/Amphaal/rpgrpz"
#define SENTRY_ENDPOINT "https://ecb72ca256e744b990fd4f50aa52ea6f@o333337.ingest.sentry.io/5517405"
